# Generated by Django 6.0.5 on 2026-05-18 06:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('university', models.CharField(max_length=200)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('thana', models.CharField(max_length=100)),
                ('union', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('unique_code', models.CharField(default=accounts.models.generate_unique_code, max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
