# Generated by Django 6.0.5 on 2026-08-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
