# Generated by Django 6.0.5 on 2026-08-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
